version: '3.7'

services:

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        entrypoint: 
            - flask
            - run 
        ports:
            - "5000:5000"
        environment:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiuser"
            MONGODB_PASSWORD: "apipassword"
        volumes:
            - appdata:/app
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./backend
